-- require 'lazyBoy112.plugins'
require 'lazyBoy112.plugins.lspconfig'
require 'lazyBoy112.plugins.gitsigns'
require 'lazyBoy112.plugins.colorizer'
require 'lazyBoy112.plugins.comment'
require 'lazyBoy112.plugins.devicon'
require 'lazyBoy112.plugins.saga'
require 'lazyBoy112.plugins.statusline'
require 'lazyBoy112.plugins.telescope'
require 'lazyBoy112.plugins.treesitter'
require 'lazyBoy112.plugins.explorer'
require 'lazyBoy112.plugins.fold'
require 'lazyBoy112.plugins.bufferline'
require 'lazyBoy112.plugins.cmp'
require 'lazyBoy112.plugins.luasnip'
require 'lazyBoy112.plugins.nui'.setup()
